# Generated by Django 5.0 on 2023-12-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('content', models.CharField(blank=True, max_length=100)),
                ('reviewer', models.IntegerField()),
                ('reviewee', models.IntegerField()),
                ('trip', models.IntegerField()),
            ],
        ),
    ]
